"$schema" = 'https://starship.rs/config-schema.json'

#[](fg:color_orange bg:color_yellow)\
#[](color_orange)\
#[ ](fg:color_bg1)\

format = """
[ ](bg:color_orange)\
$os\
$username\
[](fg:color_orange)\
[](fg:color_yellow inverted)\
$directory\
[](fg:color_yellow bg:color_aqua)\
$git_branch\
$git_status\
[](fg:color_aqua)\
$fill\
$git_metrics\
$python\
$docker_context\
$line_break$character"""

right_format="""$time"""

palette = 'gruvbox_dark'

[palettes.gruvbox_dark]
color_fg0 = '#fbf1c7'
color_fg1 = '#000000'
color_bg1 = '#3c3836'
color_bg3 = '#665c54'
color_blue = '#458588'
color_aqua = '#689d6a'
color_green = '#98971a'
color_orange = '#d65d0e'
color_purple = '#b16286'
color_red = '#cc241d'
color_yellow = '#d79921'

[os]
disabled = false
style = "bold bg:color_orange fg:color_fg0"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
EndeavourOS = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
Pop = ""

[username]
show_always = true
style_user = "bg:color_orange fg:color_fg0"
style_root = "bg:color_orange fg:color_fg1"
format = '[ $user ]($style)'

[directory]
style = "fg:color_fg0 bg:color_yellow"
format = "[ $path ]($style)"
truncation_length = 4
truncate_to_repo = false
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙"
"Downloads" = ""
"Music" = "󰝚"
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = " "
#style = "bg:color_aqua"
format = '[[ $symbol $branch ](fg:color_fg0 bg:color_aqua)]($style)'

[git_status]
style = "bg:color_aqua"
format = '[[($all_status$ahead_behind )](bold fg:color_fg0 bg:color_aqua)]($style)'

[git_metrics]
disabled = false
only_nonzero_diffs = true
added_style = "green"
deleted_style = "red"
format = ' ( [+$added]($added_style))(󰿟[-$deleted]($deleted_style)) '

[fill]
symbol = " "

[python]
symbol = ""
#style = "bg:color_blue"
format = '[[$symbol( $version) ](fg:color_blue)]($style)'

[docker_context]
symbol = ""
style = "bg:color_bg3"
format = '[[ $symbol( $context) ](fg:#83a598 bg:color_bg3)]($style)'

[time]
disabled = false
time_format = "%R %a%v"
style = "bg:color_bg1"
format = '[[  $time ](fg:color_bg3)]($style)'

[hostname]
ssh_only = false
ssh_symbol = ' '
format = '[$ssh_symbol$hostname]'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:color_green)'
error_symbol = '[](bold fg:color_red)'
vimcmd_symbol = '[](bold fg:color_green)'
vimcmd_replace_one_symbol = '[](bold fg:color_purple)'
vimcmd_replace_symbol = '[](bold fg:color_purple)'
vimcmd_visual_symbol = '[](bold fg:color_yellow)'
